package main

import "fmt"

func escrever(texto string, numeros ...int) {
	for _, numero := range numeros {
		fmt.Println(texto, numero)
	}
}

func main() {
	escrever("Ola mundo", 10, 20, 30, 100)
}

/*

FUNCÇÕES VARIATICAS
PASSANDO COMO APRAM STRING E ...N-NUMEROS
ex: ESCREVENDO UMA FRASE VARIAS VEZES CONCATENADA COM NUMEROS DIFERENTES

IMPORTANTE: Só pode ter 1 ...N-TIPO por FUNCAO E TEM QUE SEMPRE SER ANOTADO NA ULTIMA POSICAO DO PARAMETRO NA ASSINATURA
O GO TEM QUE IDENTIFICAR ONDE COMEÇA OS APRAMETROS FIXOS E ONDE TERMINA OS PARAMETROS MULTIPLOS

*/
